 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import javax.swing.JOptionPane;

/**
 *
 * @author darkcat
 */
public class GasolineCalculation extends javax.swing.JFrame {

    static final double PTT[] = {36.50, 33.24, 41.54, 29.34};
    static final double BCP[] = {37.74, 35.24, 42.64, 28.99};
    static final double SHELL[] = {37.34, 35.04, 41.84, 28.20};
    static final double ESSO[] = {37.03, 35.34, 41.55, 29.10};

    public GasolineCalculation() {
        initComponents();
    }
int i=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdbPTT = new javax.swing.JRadioButton();
        rdbBCP = new javax.swing.JRadioButton();
        rdbShell = new javax.swing.JRadioButton();
        rdbEsso = new javax.swing.JRadioButton();
        cbxCarType = new javax.swing.JComboBox<>();
        cbxOilType = new javax.swing.JComboBox<>();
        btnTax = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarTotal = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("เติมน้ำมัน");

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel2.setText("เลือกปั้ม");

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel3.setText("บาท");

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel4.setText("ประเภทน้ำมัน");

        buttonGroup1.add(rdbPTT);
        rdbPTT.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        rdbPTT.setText("ปตท");
        rdbPTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPTTActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbBCP);
        rdbBCP.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        rdbBCP.setText("บางจาก");

        buttonGroup1.add(rdbShell);
        rdbShell.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        rdbShell.setText("เชลล์");

        buttonGroup1.add(rdbEsso);
        rdbEsso.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        rdbEsso.setText("เอสโซ่");

        cbxCarType.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        cbxCarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Pickup" }));
        cbxCarType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCarTypeActionPerformed(evt);
            }
        });

        cbxOilType.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        cbxOilType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasohol 95", "Gasohol 91", "Benzin 91" }));
        cbxOilType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOilTypeActionPerformed(evt);
            }
        });

        btnTax.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnTax.setText("พิมพ์ใบกำกับภาษี");
        btnTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxActionPerformed(evt);
            }
        });

        btnReceipt.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnReceipt.setText("พิมพ์ใบเสร็จรับเงิน");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        tarTotal.setColumns(20);
        tarTotal.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tarTotal.setRows(5);
        jScrollPane1.setViewportView(tarTotal);

        btnExit.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtAmount.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel5.setText("จำนวนเงิน");

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel6.setText("ประเภทรถ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTax)
                                .addGap(111, 111, 111)
                                .addComponent(btnReceipt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxOilType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdbPTT)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbBCP)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbShell)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbEsso))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnClear)
                        .addGap(118, 118, 118)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jLabel6)
                    .addContainerGap(664, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbPTT)
                    .addComponent(rdbBCP)
                    .addComponent(rdbShell)
                    .addComponent(rdbEsso))
                .addGap(36, 36, 36)
                .addComponent(cbxCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxOilType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTax)
                    .addComponent(btnReceipt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jLabel6)
                    .addContainerGap(621, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbPTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbPTTActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed

    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
        i=1;
        String AmoutLen = txtAmount.getText();
        if (AmoutLen.length() > 0) {
            String CarType = (String) cbxCarType.getSelectedItem();
            double OilPrice = 0;
            if (rdbPTT.isSelected()) {
                String Brand = "PTT";
                Camnal(CarType, OilPrice, Brand);
            } else if (rdbBCP.isSelected()) {
                String Brand = "BCP";
                Camnal(CarType, OilPrice, Brand);
            } else if (rdbShell.isSelected()) {
                String Brand = "SHELL";
                Camnal(CarType, OilPrice, Brand);
            } else if (rdbEsso.isSelected()) {
                String Brand = "ESSO";
                Camnal(CarType, OilPrice, Brand);
            }
          
        }
    }//GEN-LAST:event_btnReceiptActionPerformed

    public void Camnal(String CarType, double OilPrice, String Brand) throws NumberFormatException {
        if (CarType == "Sedan") {
            String OilType = (String) cbxOilType.getSelectedItem();
            if (OilType == "Gasohol 95") {
                if (Brand == "PTT") {
                    OilPrice = PTT[0];
                } else if (Brand == "BCP") {
                    OilPrice = BCP[0];
                } else if (Brand == "SHELL") {
                    OilPrice = SHELL[0];
                } else if (Brand == "ESSO") {
                    OilPrice = ESSO[0];
                }
            } else if (OilType == "Gasohol 91") {
                if (Brand == "PTT") {
                    OilPrice = PTT[1];
                } else if (Brand == "BCP") {
                    OilPrice = BCP[1];
                } else if (Brand == "SHELL") {
                    OilPrice = SHELL[1];
                } else if (Brand == "ESSO") {
                    OilPrice = ESSO[1];
                }
            } else if (OilType == "Benzin 91") {
                if (Brand == "PTT") {
                    OilPrice = PTT[2];
                } else if (Brand == "BCP") {
                    OilPrice = BCP[2];
                } else if (Brand == "SHELL") {
                    OilPrice = SHELL[2];
                } else if (Brand == "ESSO") {
                    OilPrice = ESSO[2];
                }
            }
            Camnal2(OilPrice, Brand, OilType);
        } else if (CarType == "Pickup") {
            String OilType = "Diesel";
            if (Brand == "PTT") {
                OilPrice = PTT[3];
            } else if (Brand == "BCP") {
                OilPrice = BCP[3];
            } else if (Brand == "SHELL") {
                OilPrice = SHELL[3];
            } else if (Brand == "ESSO") {
                OilPrice = ESSO[3];
            }
            Camnal2(OilPrice, Brand, OilType);
        }
    }

    public void Camnal2(double OilPrice, String Brand, String OilType) throws NumberFormatException {
        String AmountString = txtAmount.getText();
        double AmountDouble = Double.valueOf(AmountString);
        double Litre = AmountDouble / OilPrice;
        double AmountPrice = AmountDouble / 1.07;
        double VAT = AmountDouble - AmountPrice;
        double Litre2 = (double) (Math.round(Litre * 100.0) / 100.0);
        double AmountPrice2 = (double) (Math.round(AmountPrice * 100.0) / 100.0);
        double VAT2 = (double) (Math.round(VAT * 100.0) / 100.0);
        if(i==0){tarTotal.setText("                  " + Brand + " Gas Station\n"
                + "                     Tax Invoice\n"
                + "-----------------------------------------------------------\n"
                + OilType + "-E10     " + Litre2 + " Litre     " + AmountDouble + " Baht\n"
                + "\n"
                + "Amount       : " + AmountPrice2 + "\n"
                + "VAT 7%       : " + VAT2 + "\n"
                + "Total Amount  : " + AmountDouble);}
        else if(i==1){
            tarTotal.setText("                  " + Brand + " Gas Station\n"
                + "                     Tax Invoice\n"
                + "-----------------------------------------------------------\n"
                + OilType + "-E10     " + Litre2 + " Litre     " + AmountDouble + " Baht\n");
        }
    }

    private void btnTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxActionPerformed
        i=0;
        
        String AmoutLen = txtAmount.getText();
        if (AmoutLen.length() > 0) {
            String CarType = (String) cbxCarType.getSelectedItem();
            double OilPrice = 0;
            if (rdbPTT.isSelected()) {
                String Brand = "PTT";
                Camnal(CarType, OilPrice, Brand);
            } else if (rdbBCP.isSelected()) {
                String Brand = "BCP";
                Camnal(CarType, OilPrice, Brand);
            } else if (rdbShell.isSelected()) {
                String Brand = "SHELL";
                Camnal(CarType, OilPrice, Brand);
            } else if (rdbEsso.isSelected()) {
                String Brand = "ESSO";
                Camnal(CarType, OilPrice, Brand);
            }
        
        }
    }//GEN-LAST:event_btnTaxActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Exit?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void cbxCarTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCarTypeActionPerformed
        String CarTypeSe = (String) cbxCarType.getSelectedItem();
        if (CarTypeSe == "Sedan") {
            cbxOilType.removeItem("Diesel");
            cbxOilType.removeItem("Diesel");
            cbxOilType.removeItem("Gasohol 95");
            cbxOilType.removeItem("Gasohol 91");
            cbxOilType.removeItem("Benzin 91");
            cbxOilType.addItem("Gasohol 95");
            cbxOilType.addItem("Gasohol 91");
            cbxOilType.addItem("Benzin 91");
        }
        if (CarTypeSe == "Pickup") {
            cbxOilType.removeItem("Gasohol 95");
            cbxOilType.removeItem("Gasohol 91");
            cbxOilType.removeItem("Benzin 91");
            cbxOilType.removeItem("Diesel");
            cbxOilType.addItem("Diesel");
            cbxOilType.setSelectedItem("Diesel");
        }
    }//GEN-LAST:event_cbxCarTypeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tarTotal.setText("");
        cbxCarType.setSelectedItem("Sedan");
        cbxOilType.setSelectedItem("Gasohol 95");
        txtAmount.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbxOilTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOilTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxOilTypeActionPerformed

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == '.')
                || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAmountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GasolineCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GasolineCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnTax;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCarType;
    private javax.swing.JComboBox<String> cbxOilType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbBCP;
    private javax.swing.JRadioButton rdbEsso;
    private javax.swing.JRadioButton rdbPTT;
    private javax.swing.JRadioButton rdbShell;
    private javax.swing.JTextArea tarTotal;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
